image: docker:latest

services:
  - docker:dind

stages:
  - build
  - docker-build
  - docker-login
  - docker-push

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_USERNAME: "prathapshanmugam5"
  DOCKER_PASSWORD: "skp20002000SKP@"

before_script:
  # Install Maven and check Docker daemon status
  - apk add --no-cache maven
  - docker info

build:
  stage: build
  script:
    # Run Maven build and ensure target directory is created
    - mvn $MAVEN_CLI_OPTS clean install
    - ls -l target
  artifacts:
    # Store the target directory as an artifact for later stages
    paths:
      - target/
    expire_in: 1 hour

docker-build:
  stage: docker-build
  script:
    # Check if target directory and JAR file exist, then build the Docker image
    - ls -l target
    - docker build -t $DOCKER_USERNAME/datacode:latest .
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker push $DOCKER_USERNAME/datacode:latest
      
  dependencies:
    - build
  only:
    - main


trigger-url:
  stage: trigger-url  # Corrected to use an existing stage
  script:
    # Trigger the URL after pushing Docker image
    - curl -X POST "https://api.render.com/deploy/srv-cqbqbiqju9rs7396972g?key=zUFKBh8MaE4"
 