image: maven:latest

stages:
  - build
  - docker-build
  - docker-login
  - docker-push

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_USERNAME: "prathapshanmugam5"
  DOCKER_PASSWORD: "skp20002000SKP@"

before_script:
  - which docker || apt-get update && apt-get install -y docker.io
  - docker info
  - sleep 10

services:
  - docker:dind
  - docker:dind-server

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install

docker-build:
  stage: docker-build
  script:
    - docker build -t prathapshanmugam5/apispring .

docker-login:
  stage: docker-login
  script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

docker-push:
  stage: docker-push
  script:
    - docker push prathapshanmugam5/apispring