
image: maven:latest

stages:
  - build
  - docker-build
  - docker-login
  - docker-push

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_USERNAME: "prathapshanmugam5"
  DOCKER_PASSWORD: "skp20002000SKP@"


before_script:
  - apt-get update && apt-get install -y docker.io
  - docker info
  - sleep 10
  - docker ps

services:
  - docker:dind

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install

docker-build:
  stage: docker-build
  script:
    - docker build -t $DOCKER_USERNAME/apispring .

docker-login:
  stage: docker-login
  script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

docker-push:
  stage: docker-push
  script:
    - docker push $DOCKER_USERNAME/apispring
